"""Automated Health Check Probe for Telemetry Service.

Verifies:
1. High-frequency 20 kHz sampling rate (20,000 Hz) compliance on industrial sensor streams
   (e.g., NASA IMS Bearing run-to-failure accelerometry fixture / PCB 353B33 high-frequency sensors).
2. ISO 10816 Zone C vibration severity threshold (4.5 mm/s RMS) enforcement and
   excursion boundary detection for rotating machinery.
"""
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import json
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Union
import uuid

from telemetry.adapters.base import DataSourceType, TelemetryAdapter
from telemetry.adapters.public_dataset import PublicDatasetReplayAdapter

logger = logging.getLogger(__name__)

# Engineering constants
TARGET_SAMPLING_RATE_HZ: float = 20000.0  # 20 kHz
TARGET_SAMPLING_RATE_KHZ: float = 20.0
ISO_10816_ZONE_C_THRESHOLD_MMS: float = 4.50  # mm/s RMS (breach into Zone C)
ISO_10816_ZONE_D_THRESHOLD_MMS: float = 7.10  # mm/s RMS (Zone D emergency trip)
STANDARD_CITATION: str = "ISO 10816-3 Class II Industrial Rotating Machinery Vibration Severity"

# Recognized aliases for Zone C (accommodating transcriptions and phonetic representations)
RECOGNIZED_ZONE_C_ALIASES = {
    "zone c",
    "jones c",
    "zone_c",
    "jones_c",
    "zonec",
    "jonesc",
    "iso 10816 zone c",
    "iso 10816 jones c",
    "iso-10816 zone c",
    "iso-10816 jones c",
    "iso 10816-3 zone c",
    "iso 10816-3 jones c",
}


@dataclass
class ProbeItemResult:
    """Individual verification check result within the health probe."""
    check_id: str
    name: str
    status: str  # "PASS" | "FAIL"
    passed: bool
    target_value: Any
    actual_value: Any
    unit: Optional[str]
    details: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "check_id": self.check_id,
            "name": self.name,
            "status": self.status,
            "passed": self.passed,
            "target_value": self.target_value,
            "actual_value": self.actual_value,
            "unit": self.unit,
            "details": self.details,
            "metadata": self.metadata,
        }


@dataclass
class TelemetryHealthReport:
    """Composite health report generated by the telemetry automated probe."""
    probe_id: str
    timestamp: str
    overall_status: str  # "HEALTHY" | "UNHEALTHY"
    all_passed: bool
    checks: Dict[str, ProbeItemResult]
    summary: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "probe_id": self.probe_id,
            "timestamp": self.timestamp,
            "overall_status": self.overall_status,
            "all_passed": self.all_passed,
            "summary": self.summary,
            "checks": {k: v.to_dict() for k, v in self.checks.items()},
            "metadata": self.metadata,
        }

    def is_healthy(self) -> bool:
        return self.all_passed


class TelemetryHealthProbe:
    """Automated health check probe for the AuRAG telemetry streaming subsystem."""

    def __init__(
        self,
        target_sampling_rate_hz: float = TARGET_SAMPLING_RATE_HZ,
        iso_zone_c_threshold_mms: float = ISO_10816_ZONE_C_THRESHOLD_MMS,
        tolerance_hz: float = 0.0,
        adapter: Optional[TelemetryAdapter] = None,
    ):
        self.target_sampling_rate_hz = float(target_sampling_rate_hz)
        self.iso_zone_c_threshold_mms = float(iso_zone_c_threshold_mms)
        self.tolerance_hz = float(tolerance_hz)
        self._adapter = adapter or PublicDatasetReplayAdapter()

    def is_recognized_zone_alias(self, alias: str) -> bool:
        """Check if the provided zone descriptor maps to ISO 10816 Zone C."""
        return alias.strip().lower() in RECOGNIZED_ZONE_C_ALIASES

    def verify_sampling_rate(
        self,
        data_or_metadata: Optional[Dict[str, Any]] = None,
        timestamps: Optional[Sequence[Union[float, str]]] = None,
        sampling_rate_hz: Optional[float] = None,
    ) -> ProbeItemResult:
        """Verify the 20 kHz sampling rate from metadata, time series deltas, or direct rate."""
        actual_hz: Optional[float] = None
        method_used = "metadata"

        if sampling_rate_hz is not None:
            actual_hz = float(sampling_rate_hz)
            method_used = "explicit_rate"
        elif timestamps is not None and len(timestamps) >= 2:
            method_used = "timestamp_delta"
            # Calculate delta between consecutive samples
            deltas: List[float] = []
            for i in range(len(timestamps) - 1):
                t0, t1 = timestamps[i], timestamps[i + 1]
                if isinstance(t0, str) and isinstance(t1, str):
                    dt = (datetime.fromisoformat(t1) - datetime.fromisoformat(t0)).total_seconds()
                else:
                    dt = float(t1) - float(t0)
                if dt > 0:
                    deltas.append(dt)
            if deltas:
                avg_dt = sum(deltas) / len(deltas)
                actual_hz = round(1.0 / avg_dt, 3)
            else:
                actual_hz = 0.0
        elif data_or_metadata is not None:
            method_used = "provided_metadata"
            actual_hz = (
                data_or_metadata.get("sampling_rate_hz")
                or data_or_metadata.get("sampling_rate")
                or data_or_metadata.get("sampling_frequency_hz")
                or (float(data_or_metadata.get("sampling_frequency_khz", 0)) * 1000.0 if "sampling_frequency_khz" in data_or_metadata else None)
            )
        else:
            method_used = "adapter_fixture"
            meta = self._adapter.get_dataset_metadata() if hasattr(self._adapter, "get_dataset_metadata") else {}
            actual_hz = meta.get("sampling_rate_hz")

        if actual_hz is None:
            return ProbeItemResult(
                check_id="CHECK-SAMPLING-RATE-20KHZ",
                name="20 kHz Telemetry Sampling Rate Verification",
                status="FAIL",
                passed=False,
                target_value=self.target_sampling_rate_hz,
                actual_value=None,
                unit="Hz",
                details="Unable to extract sampling rate from telemetry stream or metadata.",
                metadata={"verification_method": method_used},
            )

        diff = abs(actual_hz - self.target_sampling_rate_hz)
        passed = diff <= self.tolerance_hz

        if passed:
            details = (
                f"Sampling rate verified at {actual_hz:.1f} Hz (target: {self.target_sampling_rate_hz:.1f} Hz "
                f"± {self.tolerance_hz:.1f} Hz). Compliant with high-frequency PCB 353B33 accelerometry specification."
            )
            status = "PASS"
        else:
            details = (
                f"Sampling rate verification failed: observed {actual_hz:.1f} Hz, "
                f"expected {self.target_sampling_rate_hz:.1f} Hz (tolerance: {self.tolerance_hz:.1f} Hz)."
            )
            status = "FAIL"

        return ProbeItemResult(
            check_id="CHECK-SAMPLING-RATE-20KHZ",
            name="20 kHz Telemetry Sampling Rate Verification",
            status=status,
            passed=passed,
            target_value=self.target_sampling_rate_hz,
            actual_value=actual_hz,
            unit="Hz",
            details=details,
            metadata={
                "verification_method": method_used,
                "target_khz": self.target_sampling_rate_hz / 1000.0,
                "actual_khz": actual_hz / 1000.0,
                "tolerance_hz": self.tolerance_hz,
            },
        )

    def verify_iso_10816_threshold(
        self,
        zone_alias: str = "Zone C",
        custom_threshold_mms: Optional[float] = None,
        test_readings: Optional[List[Dict[str, Any]]] = None,
    ) -> ProbeItemResult:
        """Verify the ISO 10816 Zone C vibration threshold (4.5 mm/s RMS)."""
        is_alias_valid = self.is_recognized_zone_alias(zone_alias)
        expected_threshold = self.iso_zone_c_threshold_mms
        effective_threshold = custom_threshold_mms if custom_threshold_mms is not None else expected_threshold

        # Threshold calibration check
        threshold_match = abs(effective_threshold - expected_threshold) < 1e-4

        # Dynamic excursion verification using NASA IMS bearing dataset records
        records_evaluated = []
        fixture_records = test_readings
        if fixture_records is None and hasattr(self._adapter, "stream_events"):
            try:
                fixture_records = self._adapter.stream_events()
            except Exception as e:
                logger.warning("Could not retrieve stream events from adapter: %s", e)
                fixture_records = []

        excursion_detected_correctly = True
        nominal_classified_correctly = True

        if fixture_records:
            for rec in fixture_records:
                vib = float(rec.get("vibration_mm_s", 0.0))
                rec_id = rec.get("provenance", {}).get("dataset_record_id") or rec.get("record_id", "REC")
                is_excursion = vib > effective_threshold
                records_evaluated.append({
                    "record_id": rec_id,
                    "vibration_mm_s": vib,
                    "excursion": is_excursion,
                    "flagged_threshold_exceeded": bool(rec.get("threshold_exceeded", is_excursion)),
                })
                # Check known canonical baseline: REC-001 (1.85 mm/s) must be nominal
                if rec_id == "NASA-IMS-T2-REC-001" and is_excursion:
                    nominal_classified_correctly = False
                # Check canonical anomaly: REC-042 (5.42 mm/s) must be excursion
                if rec_id == "NASA-IMS-T2-REC-042" and not is_excursion:
                    excursion_detected_correctly = False

        passed = is_alias_valid and threshold_match and excursion_detected_correctly and nominal_classified_correctly

        if passed:
            details = (
                f"ISO 10816 {zone_alias} threshold verified at {expected_threshold:.2f} mm/s RMS. "
                f"Governing standard: {STANDARD_CITATION}. "
                f"Boundary discrimination validated (sub-threshold nominals pass; excursion breaches trigger alarm)."
            )
            status = "PASS"
        else:
            reasons = []
            if not is_alias_valid:
                reasons.append(f"Unrecognized zone identifier '{zone_alias}'")
            if not threshold_match:
                reasons.append(f"Configured threshold {effective_threshold} does not match {expected_threshold}")
            if not excursion_detected_correctly:
                reasons.append("Failed to detect Zone C excursion on high vibration record")
            if not nominal_classified_correctly:
                reasons.append("False alarm on sub-threshold baseline record")
            details = f"ISO 10816 {zone_alias} threshold check failed: {'; '.join(reasons)}."
            status = "FAIL"

        return ProbeItemResult(
            check_id="CHECK-ISO-10816-ZONE-C-THRESHOLD",
            name="ISO 10816 Zone C Threshold Verification",
            status=status,
            passed=passed,
            target_value=expected_threshold,
            actual_value=effective_threshold,
            unit="mm/s",
            details=details,
            metadata={
                "zone_alias": zone_alias,
                "canonical_zone": "Zone C",
                "standard": STANDARD_CITATION,
                "records_evaluated_count": len(records_evaluated),
                "evaluation_samples": records_evaluated[:5],
                "zone_d_trip_threshold_mms": ISO_10816_ZONE_D_THRESHOLD_MMS,
            },
        )

    def verify_boundary_discrimination(self) -> ProbeItemResult:
        """Verify strict boundary behavior around exactly 4.50 mm/s RMS."""
        # 4.49 mm/s -> sub-threshold (Zone B)
        # 4.50 mm/s -> boundary limit
        # 4.51 mm/s -> Zone C excursion breach
        test_points = [
            (4.49, False),
            (4.50, False),
            (4.51, True),
            (5.42, True),
            (11.75, True),
        ]
        failures = []
        for vib, expected_breach in test_points:
            actual_breach = vib > self.iso_zone_c_threshold_mms
            if actual_breach != expected_breach:
                failures.append(f"Value {vib} mm/s: expected excursion={expected_breach}, got {actual_breach}")

        passed = len(failures) == 0
        status = "PASS" if passed else "FAIL"
        details = (
            f"Boundary discrimination validated across {len(test_points)} test points "
            f"around {self.iso_zone_c_threshold_mms:.2f} mm/s threshold."
            if passed else f"Boundary discrimination failed: {', '.join(failures)}"
        )
        return ProbeItemResult(
            check_id="CHECK-BOUNDARY-DISCRIMINATION",
            name="ISO 10816 Zone C Boundary Discrimination",
            status=status,
            passed=passed,
            target_value=self.iso_zone_c_threshold_mms,
            actual_value=self.iso_zone_c_threshold_mms,
            unit="mm/s",
            details=details,
            metadata={"test_points": test_points},
        )

    def verify_stream_pipeline(self) -> ProbeItemResult:
        """Verify the public dataset replay pipeline delivers valid telemetry events."""
        try:
            events = self._adapter.stream_events()
            count = len(events)
            has_records = count >= 4
            has_rec42 = any(
                e.get("provenance", {}).get("dataset_record_id") == "NASA-IMS-T2-REC-042"
                or e.get("vibration_mm_s") == 5.42
                for e in events
            )
            passed = has_records and has_rec42
            status = "PASS" if passed else "FAIL"
            details = (
                f"Telemetry pipeline verified with {count} streamed events from NASA IMS bearing dataset."
                if passed else "Telemetry pipeline missing records or excursion record REC-042."
            )
            return ProbeItemResult(
                check_id="CHECK-TELEMETRY-STREAM-PIPELINE",
                name="Telemetry Stream Ingestion & Normalization Pipeline",
                status=status,
                passed=passed,
                target_value="NASA IMS Replay Active",
                actual_value=f"{count} events parsed",
                unit="records",
                details=details,
                metadata={"event_count": count},
            )
        except Exception as exc:
            return ProbeItemResult(
                check_id="CHECK-TELEMETRY-STREAM-PIPELINE",
                name="Telemetry Stream Ingestion & Normalization Pipeline",
                status="FAIL",
                passed=False,
                target_value="NASA IMS Replay Active",
                actual_value="ERROR",
                unit="records",
                details=f"Pipeline exception: {str(exc)}",
            )

    def run_probe(self, include_pipeline: bool = True) -> TelemetryHealthReport:
        """Run the full automated probe suite and compile a TelemetryHealthReport."""
        probe_id = f"PROBE-TEL-{uuid.uuid4().hex[:8].upper()}"
        ts = datetime.now(timezone.utc).isoformat()

        checks: Dict[str, ProbeItemResult] = {}
        # 1. 20 kHz sampling rate check
        checks["sampling_rate_20khz"] = self.verify_sampling_rate()

        # 2. ISO 10816 Zone C threshold check
        checks["iso_10816_zone_c_threshold"] = self.verify_iso_10816_threshold(zone_alias="Zone C")

        # 3. Boundary discrimination check
        checks["boundary_discrimination"] = self.verify_boundary_discrimination()

        # 4. Optional stream pipeline check
        if include_pipeline:
            checks["stream_pipeline"] = self.verify_stream_pipeline()

        all_passed = all(check.passed for check in checks.values())
        overall_status = "HEALTHY" if all_passed else "UNHEALTHY"
        summary = (
            f"All {len(checks)} automated telemetry health checks PASSED. "
            f"20 kHz sampling rate verified. ISO 10816 Zone C threshold (4.50 mm/s) enforced."
            if all_passed else
            f"Telemetry health checks DEGRADED: "
            f"{', '.join(k for k, v in checks.items() if not v.passed)} failed."
        )

        return TelemetryHealthReport(
            probe_id=probe_id,
            timestamp=ts,
            overall_status=overall_status,
            all_passed=all_passed,
            checks=checks,
            summary=summary,
            metadata={
                "target_sampling_rate_hz": self.target_sampling_rate_hz,
                "iso_10816_threshold_mms": self.iso_zone_c_threshold_mms,
                "standard": STANDARD_CITATION,
            },
        )


def run_telemetry_health_check(
    probe: Optional[TelemetryHealthProbe] = None,
    **probe_kwargs: Any,
) -> TelemetryHealthReport:
    """Convenience entry point for running the telemetry health check probe."""
    active_probe = probe or TelemetryHealthProbe(**probe_kwargs)
    return active_probe.run_probe()
